### ISSUE TITLE
composer.lock issue

### ISSUE THREAD

**Issue by ruslan3309** [iuthub/ip-group-project-mates-guest-house#1]
Unable to run the project since
In ProviderRepository.php line 208:
  Class 'Collective\Html\HtmlServiceProvider' not found

**Comment by donik1998** [comment]
I will try to re-deploy the project

**Comment by donik1998** [comment]
It is done. It seems to be working

**Comment by youtubeuz** [comment]
Yeah, I suppose you haven't implemented laravelcollective.
